### ISSUE TITLE
Responsive design improvement

### ISSUE THREAD

**Issue by hacfi** [vespolina/VespolinaAdminBundle#2]
Hi @inspiran, hi everyone,
so making the admin order list responsive my idea would be to make the list a little "lighter" by:
- putting the customer name next to the order no
- maybe write "#213" instead of "Order 213"
- replace the written order status with an icon (using http://fortawesome.github.com/Font-Awesome/ ?)
- put the number of items in a label next to the order status
- remove order amount (depends on how much space there is left)

My quick draft (missing point 2):
![vespolina-admin-list](https://f.cloud.github.com/assets/428841/187240/13e037e8-7d4e-11e2-90a8-c47116acb403.jpg)

If you select a order the list slides away to the left and the order details come in from the right.

If we use tables for the list we should work with the ZURB Responsive Tables: http://www.zurb.com/playground/responsive-tables

I actually don't have a working copy of Vespolina but you need help working on this let me know!

P.S: Not sure if this is useful in this case but check out http://fittextjs.com/

**Comment by cordoval** [comment]
:+1:

**Comment by cordoval** [comment]
wow this was old, thanks for the closure

**Comment by hacfi** [comment]
Yep..cleaning up my issues :)
